# MailGun
MAILGUN:
  API_KEY: key-30b2e4668a7145041e8af530c7ce21b6
  DOMAIN: sandbox50c6553b84594392b9f43067c24a42a0.mailgun.org
SENDGRID:
  API_KEY: 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
SENDER:
  NAME: One Heck of an Excited User
  EMAIL: <someone@emailprovider.com>
